### PR TITLE
Finished details and open pull request for code review

### PR DESCRIPTION
**Pull request by jfariasf**

### CODE REVIEW

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work team :clap: . However, some requirements needs to be implemented in order for us to approve your project. check below :arrow_down: .

#### Page structure

##### Intuit logo

* [x] It shows the Intuit logo above the form.
* [x] The intuit logo is an embedded image that is horizontally centered.

##### Intuit products

* [x] The products row is under the Intuit logo and above the form.
* [x] It shows the Mint logo and text (logo on the left, text on the right).
* [x] It shows the Quickbooks logo and text (logo on the left, text on the right).
* [x] It shows the Turbotax logo and text (logo on the left, text on the right).

> **I see the code for these two sections but it's not showing up**

##### Form


###### Middle

* [x] All the labels are displayed above the input.
- **[REQUIRED]** Add `for="id_of_input"` to each label to link it with its corresponding input.

https://github.com/jfariasf/mint-signup-form-clone/blob/83f53223b7cc5f27c9bf129f68db3c860d9b9c9a/index.html#L74-L80
- **Implementation** : you have an extra div here :arrow_double_up: 

#### General requirements:

* [x] The project has a descriptive README.md

* [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.

### That's it :relaxed: . When finsihed, kindly resubmit another code review request :pray: .

**Comment by wickathou** [comment]
@stratospherique I'm quite confused with the review, could you post a small video or screenshots? While working on it and just open it again following your review and the page is looking as you can see on these screenshots.

Ours
https://www.dropbox.com/s/bkxs9991k00j59i/Screenshot%202019-09-23%2023.01.48.png?dl=0

Original:
https://www.dropbox.com/s/4ddfs1j4j7x3g0s/Screenshot%202019-09-23%2023.04.13.png?dl=0

**Comment by wickathou** [comment]
Fixed:
- Relative path for images
- w3c validator errors on the labels
- Extra empty div tag removed
- Readme file updated

**Review by stratospherique — APPROVED** [review]
### Great work :clap: . You made all the necessary changes :100: . You project is approved :heavy_check_mark:  and you can merge to master :+1: :+1: .

###### PS: add live preview link of the page that you designed to your readme file :smile:

**Pull request merged**
